services:
  - type: web
    name: anonpay-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: PORT
        value: 4000
      - key: FRONTEND_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: MIDNIGHT_INDEXER_URL
        sync: false
      - key: ANONPAY_CONTRACT_ADDRESS
        sync: false
      - key: PROVABLE_API_KEY
        sync: false
      - key: PROVABLE_CONSUMER_ID
        sync: false
      - key: RELAYER_PRIVATE_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_GEMINI_MODEL
        sync: false
      - key: GOOGLE_GEMINI_MODELS
        sync: false
