-- Bootstrap schema for a fresh Supabase project.
-- Run this first in the Supabase SQL editor before any ALTER TABLE migrations.

create extension if not exists pgcrypto;

create table if not exists public.merchants (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    encrypted_midnight_address text not null,
    encrypted_secret_key text,
    secret_key_hash text unique,
    encrypted_webhook_url text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    address_hash text not null unique,
    main_address text,
    burner_address text,
    encrypted_burner_key text,
    profile_main_invoice_hash text,
    profile_burner_invoice_hash text,
    encrypted_address_check text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
    id bigint generated by default as identity primary key,
    invoice_id text,
    invoice_hash text not null unique,
    merchant_address text not null,
    designated_address text,
    merchant_address_hash text,
    is_burner boolean not null default false,
    payer_address text,
    amount numeric,
    memo text,
    status text not null default 'PENDING',
    invoice_transaction_id text,
    payment_tx_id text,
    payment_tx_ids text[],
    salt text,
    expiry text,
    invoice_type smallint not null default 0,
    token_type smallint not null default 0,
    invoice_items jsonb,
    for_sdk boolean not null default false,
    receipt_commitment text,
    tx_hash text,
    block_height bigint,
    block_settled bigint,
    settled_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.payment_intents (
    id uuid primary key default gen_random_uuid(),
    merchant_id uuid not null references public.merchants(id) on delete cascade,
    amount numeric not null default 0,
    token_type text,
    invoice_type smallint not null default 0,
    status text not null default 'PENDING',
    invoice_hash text,
    salt text,
    success_url text,
    cancel_url text,
    checkout_url text,
    tx_id text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.disclosures (
    proof_id uuid primary key,
    invoice_id text,
    reveal_amount boolean,
    reveal_date boolean,
    reveal_status boolean,
    recipient_description text,
    amount bigint,
    settled_at timestamptz,
    status text,
    created_at timestamptz not null default now()
);

create index if not exists idx_merchants_address on public.merchants(encrypted_midnight_address);
create index if not exists idx_users_address_hash on public.users(address_hash);
create index if not exists idx_invoices_created_at on public.invoices(created_at desc);
create index if not exists idx_invoices_status on public.invoices(status);
create index if not exists idx_invoices_merchant_address on public.invoices(merchant_address);
create index if not exists idx_invoices_merchant_address_hash on public.invoices(merchant_address_hash);
create index if not exists idx_invoices_invoice_id on public.invoices(invoice_id);
create index if not exists idx_invoices_invoice_transaction_id on public.invoices(invoice_transaction_id);
create index if not exists idx_invoices_tx_hash on public.invoices(tx_hash);
create index if not exists idx_invoices_for_sdk on public.invoices(for_sdk);
create index if not exists idx_payment_intents_merchant_id on public.payment_intents(merchant_id);
create index if not exists idx_payment_intents_status on public.payment_intents(status);
create index if not exists idx_payment_intents_invoice_hash on public.payment_intents(invoice_hash);
create index if not exists idx_disclosures_invoice_id on public.disclosures(invoice_id);

create index if not exists idx_invoices_payment_tx_ids on public.invoices using gin (payment_tx_ids);

alter table public.merchants disable row level security;
alter table public.users disable row level security;
alter table public.invoices disable row level security;
alter table public.payment_intents disable row level security;
alter table public.disclosures disable row level security;
